pipeline:
  name: app-cicd-pipeline
  identifier: app_cicd_pipeline
  orgIdentifier: default
  projectIdentifier: infraterraform
  stages:
    - stage:
        name: Build_Backend_Frontend
        identifier: Build_Images
        type: CI
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Abort
        spec:
          execution:
            steps:
              - step:
                  name: Build_Push_Backend
                  identifier: build_push_backend
                  type: BuildAndPushDockerRegistry
                  spec:
                    delegateSelectors:
                      - docker-delegate
                    connectorRef: aws_ecr_conn
                    repo: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/backend
                    tags:
                      - ${BUILD_ID}
                      - latest
                    dockerfile: app/backend/Dockerfile
                    context: app/backend/
                    timeout: 10m
              - step:
                  name: Build_Push_Frontend
                  identifier: build_push_frontend
                  type: BuildAndPushDockerRegistry
                  spec:
                    delegateSelectors:
                      - docker-delegate
                    connectorRef: aws_ecr_conn
                    repo: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/frontend
                    tags:
                      - ${BUILD_ID}
                      - latest
                    dockerfile: app/frontend/Dockerfile
                    context: app/frontend/
                    timeout: 10m
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: eksdevcluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              harnessImageConnectorRef: account.harnessImage
              os: Linux
    - stage:
        name: Deploy_To_EKS
        identifier: Deploy_K8s
        type: Deployment
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: dev_env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: eksdevinfra
          service:
            serviceRef: app_service
          execution:
            steps:
              - step:
                  name: Deploy_Kustomize
                  identifier: deploy_kustomize
                  type: K8sApply
                  spec:
                    filePaths:
                      - kustomization.yaml
                    delegateSelectors:
                      - docker-delegate
                    manifests:
                      - manifest:
                          identifier: k8s-app
                          type: Kustomize
                          spec:
                            store:
                              type: GitHub
                              spec:
                                connectorRef: gitterraform
                                repoName: marriott-sr-devops-test
                                branch: main
                                folderPath: k8s/
                    timeout: 10m
            rollbackSteps: []
  variables:
    - name: AWS_ACCOUNT_ID
      type: String
      value: "790779513290"

